### ISSUE TITLE
Coult not write rx - glasses crash

### ISSUE THREAD

**Issue by PixelSnake** [ActiveLook/android-sdk#16]
Hi there,

I am experiencing a strange issue. Sometimes after disconnecting and reconnecting to the glasses without turning them off in between, the following error message is logged to Logcat thousands of times, eventually followed by a StackOverflowException. Unfortunately I cannot reliably reproduce the error, sometimes it happens, sometimes it doesn't.

The biggest issue with this is that it crashes the glasses to the point where I am unable to turn them off by long pressing the power button. I tried holding the power button for a very long time (~10s) and eventually the glasses turned off but refused to turn back on. They can be reset by connecting them to the charging cable after which everything starts working normally.

Package name is replaced by xxxxxxxxx due to an NDA and for privacy reasons.

```
2024-01-11 10:21:49.388 26838-26906 unstackWri...acteristic de....xxxxxxxxxxxxxx  E  Error, retry
2024-01-11 10:21:49.396 26838-26906 unstackWri...risticLoop de....xxxxxxxxxxxxxx  E  Could not write rx: FF37011C4D00C8006404FFFF4E6F206461746120736F7572636500AA
```

```
FATAL EXCEPTION: Thread-8
Process: xxxxxxxxxx, PID: 27035
java.lang.StackOverflowError: stack size 1039KB
	at java.util.ArrayList$Itr.<init>(ArrayList.java:974)
	at java.util.ArrayList.iterator(ArrayList.java:954)
	at com.activelook.activelooksdk.core.ble.GlassesGattCallbackImpl.lambda$unstackWriteRxCharacteristicLoop$4(GlassesGattCallbackImpl.java:399)
	at com.activelook.activelooksdk.core.ble.GlassesGattCallbackImpl$$ExternalSyntheticLambda2.accept(Unknown Source:4)
	at com.activelook.activelooksdk.core.ble.GlassesGattCallbackImpl.lambda$unstackWriteRxCharacteristicLoop$3(GlassesGattCallbackImpl.java:369)
	at com.activelook.activelooksdk.core.ble.GlassesGattCallbackImpl$$ExternalSyntheticLambda1.run(Unknown Source:2)
	at com.activelook.activelooksdk.core.ble.GlassesGattCallbackImpl.lambda$unstackWriteRxCharacteristicLoop$4(GlassesGattCallbackImpl.java:399)
	at com.activelook.activelooksdk.core.ble.GlassesGattCallbackImpl$$ExternalSyntheticLambda2.accept(Unknown Source:4)
	at com.activelook.activelooksdk.core.ble.GlassesGattCallbackImpl.lambda$unstackWriteRxCharacteristicLoop$3(GlassesGattCallbackImpl.java:369)
	at com.activelook.activelooksdk.core.ble.GlassesGattCallbackImpl$$ExternalSyntheticLambda1.run(Unknown Source:2)
	at com.activelook.activelooksdk.core.ble.GlassesGattCallbackImpl.lambda$unstackWriteRxCharacteristicLoop$4(GlassesGattCallbackImpl.java:399)
	at com.activelook.activelooksdk.core.ble.GlassesGattCallbackImpl$$ExternalSyntheticLambda2.accept(Unknown Source:4)
```

**Comment by SylvainRomillon** [comment]
Hi,

Thank you for your interest and your feedback.

In order to reproduce issue, could you please provide us : 
- [glasses firmware version](https://github.com/ActiveLook/android-sdk/blob/main/ActiveLookSDK/src/main/java/com/activelook/activelooksdk/types/DeviceInformation.java#L59)
- [glasses settings](https://github.com/ActiveLook/android-sdk/blob/main/ActiveLookSDK/src/main/java/com/activelook/activelooksdk/core/AbstractGlasses.java#L290C22-L290C22)
- [glasses battery Level](https://github.com/ActiveLook/android-sdk/blob/main/ActiveLookSDK/src/main/java/com/activelook/activelooksdk/core/AbstractGlasses.java#L262)
- log of commands used before disconnecting and after reconnecting

Thank you

**Comment by thomaschapelle** [comment]
Closing this as it as no response from issuer. If this is still relevant, please reopen with details asked.
