### ISSUE TITLE
HTTP 404 error when trying to update firmware

### ISSUE THREAD

**Issue by slastowski** [ActiveLook/android-sdk#18]
Hi,

when SDK.init() is called, there's a HTTP 404 error causing firmware update to fail:
```
UPDATE      D  Create update task for: DeviceInformation{manufacturerName='Microoled ', modelNumber='ENGO 2 ', serialNumber='**********', hardwareVersion='ALK02C', firmwareVersion='v4.12.1b', softwareVersion='1.0.0.1', batteryLevel='99'}
Volley      E  [117] NetworkUtility.shouldRetryException: Unexpected response code 404 for https://fw.activelook.net/v1/firmwares/ALK02C/?compatibility=4&min-version=4.12.1
System.err  W  com.android.volley.ClientError
System.err  W  	at com.android.volley.toolbox.NetworkUtility.shouldRetryException(NetworkUtility.java:193)
System.err  W  	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:145)
System.err  W  	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:132)
System.err  W  	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
System.err  W  	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)
```
ActiveLook Android SDK 4.5.5 is used. Application running on Google Pixel 6, Android 15 Beta.

**Comment by SylvainRomillon** [comment]
Hi,

I apologize for the delayed response.
This is expected behavior. It's designed to check for available firmware updates in our applications.
